[versions]
protobuf = "4.29.3"
coroutine = "1.10.1"
kotlin = "2.1.10"

[plugins]
kotlin = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
agp-app = { id = "com.android.application", version = "8.8.1" }
protobuf = { id = "com.google.protobuf", version = "0.9.4" }
lsplugin-jgit = { id = "org.lsposed.lsplugin.jgit", version = "1.1" }
lsplugin-resopt = { id = "org.lsposed.lsplugin.resopt", version = "1.6" }
lsplugin-apksign = { id = "org.lsposed.lsplugin.apksign", version = "1.4" }
lsplugin-apktransform = { id = "org.lsposed.lsplugin.apktransform", version = "1.2" }
lsplugin-cmaker = { id = "org.lsposed.lsplugin.cmaker", version = "1.2" }

[libraries]
xposed = { module = "de.robv.android.xposed:api", version = "82" }
cxx = { module = "org.lsposed.libcxx:libcxx", version = "27.0.12077973" }
protobuf-kotlin = { module = "com.google.protobuf:protobuf-kotlin-lite", version.ref = "protobuf" }
protobuf-java = { module = "com.google.protobuf:protobuf-javalite", version.ref = "protobuf" }
protobuf-protoc = { module = "com.google.protobuf:protoc", version.ref = "protobuf" }
kotlin-stdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib", version.ref = "kotlin" }
kotlin-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "coroutine" }
kotlin-coroutines-jdk = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-jdk8", version.ref = "coroutine" }
androidx-documentfile = { module = "androidx.documentfile:documentfile", version = "1.0.1" }
